controllers:
  Elbow:
    position: {d: 0, i: 0, p: 1}
    velocity: {d: 0, i: 0, p: 1}
  Shoulder:
    position: {d: 0, i: 0, p: 1}
    velocity: {d: 0, i: 0, p: 1}
  Slew:
    position: {d: 0, i: 0, p: 1}
    velocity: {d: 0, i: 0, p: 1}
  config:
    body: {cascaded_position: false, command: body_command, dynamic_reconfigure: true,
      setpoint: body_setpoint, state: body_state}
    joints: {cascaded_position: false, command: joint_command, dynamic_reconfigure: true,
      setpoint: joint_setpoint, state: joint_states}
  pitch:
    position: {d: 0, i: 0, p: 1}
    velocity: {d: 0, i: 0, p: 1}
  x:
    position: {d: 0, i: 0, p: 1}
    velocity: {d: 0, i: 0, p: 1}
  y:
    position: {d: 0, i: 0, p: 1}
    velocity: {d: 0, i: 0, p: 1}
  yaw:
    position: {d: 0, i: 0, p: 1}
    velocity: {d: 0, i: 0, p: 1}
  z:
    position: {d: 0, i: 0, p: 1}
    velocity: {d: 0, i: 0, p: 1}
