controllers:
    config:
        body:
            control_type: thruster  # cannot be wrench anyway because of steering thrusters
            state: state
            setpoint: body_setpoint
            command: body_command
            cascaded_position: False
            dynamic_reconfigure: True
        joints:
            state: joint_states
            setpoint: joint_setpoint
            command: joint_command
            cascaded_position: False
            dynamic_reconfigure: True
    x:
        velocity: {p: 150, i: 100, d: 0}
        position: {p: 100, i: 5, d: 100}
    y:
        velocity: {p: 150, i: 100, d: 0}
        position: {p: 100, i: 5, d: 100}
    z:
        velocity: {p: 150, i: 100, d: 0}
        position: {p: 100, i: 5, d: 100}
    pitch:
        velocity: {p: 150, i: 100, d: 0}
        position: {p: 100, i: 5, d: 100}
    yaw:
        velocity: {p: 150, i: 100, d: 0}
        position: {p: 100, i: 5, d: 100}
    fwd_left:
        velocity: {p: 1.0, i: 0., d: 0.0}
        position: {p: 10, i: 0.1, d: 0.5}
    fwd_right:
        velocity: {p: 1.0, i: 0., d: 0.0}
        position: {p: 10, i: 0.1, d: 0.5}
        